site_name: MR Joao Bresser
docs_dir: docsmd # onde acha o md
nav:
    - Home: index.md
    - Projetos: projetos.md
theme:
    name: simple-blog
    custom_dir: project_files/custom_theme/
    language: pt-br
extra_css:
    - custom.css
extra_javascript:
    - js/copy-button.js
plugins:
    - youtube
    - resize_image
    - stack_nav
    - search
markdown_extensions:
    - markdown.extensions.extra
    - markdown.extensions.codehilite
