site_name: MR Joao Bresser
docs_dir: docsmd # onde acha o md
nav:
    - Home: index.md
    - legal: home.md
    - Projetos: nuvem.md
theme:
    name: simple-blog
    custom_dir: custom_theme/
extra_css:
    - custom.css
extra_javascript:
    - js/copy-button.js
plugins:
    - youtube
    - search
markdown_extensions:
    - markdown.extensions.extra
    - markdown.extensions.codehilite
